# Generated by Django 5.2.5 on 2025-09-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testride',
            name='user',
        ),
    ]
