# Generated by Django 5.2.5 on 2025-09-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0002_remove_booking_user_remove_testride_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='testride',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
    ]
