# Generated by Django 5.2.5 on 2025-09-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0003_booking_price_testride_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='testride',
            name='price',
            field=models.CharField(default=10000, max_length=10),
        ),
    ]
