# Generated by Django 5.2.5 on 2025-09-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0004_alter_booking_price_alter_testride_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='testride',
            name='price',
        ),
    ]
