# Generated by Django 5.2.5 on 2025-09-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0007_alter_bikecollections_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikecollections',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
