# Generated by Django 5.2.5 on 2025-09-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0009_booking_user_testride_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testride',
            name='user',
        ),
    ]
