# Generated by Django 5.2.5 on 2025-09-14 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0010_remove_booking_user_remove_testride_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='testride',
            name='testride_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
